logging.file: logs/application.log
server:
  port: 9083
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: DEBUG
spring:
  datasource:
    url:  jdbc:h2:file:./h2/org
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
